import type { ActivityEvent, Issue, Job, JobStage } from "@/types/core";

export const jobStages: JobStage[] = [
  "RFQ Intake",
  "Drawing Review",
  "Capability Check",
  "Quote Draft",
  "Quote Approved",
  "PO Intake",
  "Job Released",
  "Build Readiness",
  "In Progress",
  "Quality Review",
  "Ready to Ship",
  "Shipped",
];

export const demoJobs: Job[] = [
  {
    id: "job-1048",
    jobNumber: "1048",
    customer: "Acme Robotics",
    part: "Bracket Rev C",
    revision: "C",
    dueDate: "Jun 14",
    owner: "John Doe",
    machine: "Haas VF-2",
    quantityComplete: 72,
    quantityTotal: 100,
    risk: "medium",
    stage: "In Progress",
    status: "in_progress",
    issueCount: 0,
  },
  {
    id: "job-1051",
    jobNumber: "1051",
    customer: "Northline Medical",
    part: "Valve Body",
    revision: "A",
    dueDate: "May 22",
    owner: "Maria Chen",
    machine: "Doosan Lynx",
    quantityComplete: 0,
    quantityTotal: 40,
    risk: "high",
    stage: "Build Readiness",
    status: "blocked",
    issueCount: 2,
  },
  {
    id: "job-1055",
    jobNumber: "1055",
    customer: "Kestrel Labs",
    part: "Sensor Housing",
    revision: "B",
    dueDate: "May 24",
    owner: "Andre Hill",
    quantityComplete: 25,
    quantityTotal: 25,
    risk: "low",
    stage: "Quality Review",
    status: "inspection",
    issueCount: 0,
  },
  {
    id: "job-1058",
    jobNumber: "1058",
    customer: "Harbor Systems",
    part: "Mount Plate",
    revision: "D",
    dueDate: "May 18",
    owner: "Nina Patel",
    quantityComplete: 12,
    quantityTotal: 12,
    risk: "low",
    stage: "Ready to Ship",
    status: "ready_to_ship",
    issueCount: 0,
  },
];

export const demoIssues: Issue[] = [
  {
    id: "issue-1",
    title: "Material cert missing for 6061 bar stock",
    severity: "medium",
    target: "Job 1051",
    owner: "Maria Chen",
    status: "open",
  },
  {
    id: "issue-2",
    title: "VF-2 coolant alarm needs review",
    severity: "high",
    target: "Machine Haas VF-2",
    owner: "John Doe",
    status: "open",
  },
  {
    id: "issue-3",
    title: "PO date differs from quoted delivery",
    severity: "medium",
    target: "Job 1055",
    owner: "Andre Hill",
    status: "open",
  },
];

export const demoActivity: ActivityEvent[] = [
  {
    id: "activity-1",
    message: "Corvus parsed a staff update for Job 1048: 72/100 complete.",
    timestamp: "11:42 AM",
    actor: "corvus",
  },
  {
    id: "activity-2",
    message: "Maria opened an issue against Job 1051.",
    timestamp: "10:18 AM",
    actor: "user",
  },
  {
    id: "activity-3",
    message: "Job 1058 moved to Ready to Ship.",
    timestamp: "9:36 AM",
    actor: "system",
  },
];
